### ISSUE TITLE
`glasskube telemetry disable` does nothing to the cluster?

### ISSUE THREAD

**Issue by cdrage** [glasskube/glasskube#897] opened 2024-06-27 13:38 UTC
**Describe the bug**

After using `glasskube telemetry disable` I expect something to be done to the operator / cluster to disable telemetry?

Although it looks like there is no confirmation / changes / other confirmations that it's actually been done?

**To Reproduce**
Do `glasskube telemetry disable`

**Expected behavior**

Expect it to do something to the cluster?

**Screenshots**

N/A

**Cluster Info (please complete the following information):**

N/A

**Glasskube Info (please complete the following information):**

```
glasskube version

  ____ _        _    ____ ____  _  ___   _ ____  _____
 / ___| |      / \  / ___/ ___|| |/ / | | | __ )| ____|
| |  _| |     / _ \ \___ \___ \| ' /| | | |  _ \|  _|
| |_| | |___ / ___ \ ___) |__) | . \| |_| | |_) | |___
 \____|_____/_/   \_\____/____/|_|\_\\___/|____/|_____|

glasskube: v0.11.0
package-operator: v0.11.0
```

**Additional context**

**Comment by christophenne** [comment] 2024-07-02 09:46
@cdrage the `glasskube telemetry disable` command should set the value of the `packages.glasskube.dev/telemetry-enabled` annotation in your `glasskube-system` namespace to `false`. If it did not do that, that's an actual bug, however I could not reproduce this on my side. Could you please check again whether this annotation has been set to `false`?

**Comment by pmig** [comment] 2024-07-30 14:58
Closing this issues as it already works as expected.

**Closed by pmig** 2024-07-30 14:58 UTC
Labels: bug, needs-triage
